version: "3.8"

services:
  backend:
    image: your-dockerhub-user/myapp-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: your-dockerhub-user/myapp-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: